### ISSUE TITLE
Creación de Paquetes para implementar la Capa Service

### ISSUE THREAD

**Issue by NikoVelazco** [NikoVelazco/repositorio-tp2#109]
Cree los paquetes ar.edu.unju.fi.service y ar.edu.unju.fi.service.imp.
Agregue al paquete ar.edu.unju.fi.service la interfaz IProductoService, realice la codificación necesaria para el funcionamiento del proyecto.
Agregue al paquete ar.edu.unju.fi.service.imp la clase ProductoServiceImp con su codificación completa.

**Comment by cristianortega0** [comment]
Tarea terminada
