### ISSUE TITLE
Modificar la clase Sucursal

### ISSUE THREAD

**Issue by cristianortega0** [NikoVelazco/repositorio-tp2#150]
En la clase Sucursal debe agregar:
Anotaciones pertenecientes al paquete jakarta.persistence (@Entity, @Table, @Id, @Column)
Un atributo de tipo Long con nombre id y notación @Id.
El nombre de la columna (@Column) para cada atributo de las clases
Agregue un atributo de tipo boolean denominado estado, este atributo indica si el objeto está activo o no. Si se quiere eliminar un objeto se utilizará el estado = false, cuando se crea un nuevo objeto el estado siempre tiene valor true

**Comment by SaraDMercado** [comment]
Tarea realizada
